spring:
  cloud:
    config:
      enabled: false
    function:
      definition: processStyleKStream
    stream:
      #default-binder: kafka
      bindings:
        processStyleKStream-in-0:
          destination: TP.STYLE
          content-type: application/*+avro
          group: CG.STYLE.STREAM
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultipler: 2
            backOffMaxInterval: 8000
        processStyle-in-0:
          destination: TP.STYLE
          content-type: application/*+avro
          group: CG.STYLE
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultipler: 2
            backOffMaxInterval: 8000
        processStyleBatch-in-0:
          destination: TP.STYLE.BATCH
          content-type: application/*+avro
          group: CG.STYLE.BATCH
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultipler: 2
            backOffMaxInterval: 8000
            batchMode: true
      kafka.streams:
        binder:
          auto-create-topics: false
          brokers: localhost:9092
          configuration:
            #default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            #default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            schema.registry.url: http://localhost:8081
        bindings:
          processStyleKStream-in-0:
            consumer:
              destination: TP.STYLE
              content-type: application/*+avro
              group: CG.STYLE.STREAM
              enableDlq: false
              autoCommitOffset: true
              key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
              #useNativeDecoding: true
          processStyle-in-0:
            consumer:
              destination: TP.STYLE
              content-type: application/*+avro
              group: CG.STYLE
              enableDlq: false
              autoCommitOffset: false
          processStyleBatch-in-0:
            consumer:
              destination: TP.STYLE.BATCH
              content-type: application/*+avro
              group: CG.STYLE.BATCH
              configuration:
                max.poll.records: 10
                fetch.min.bytes: 10000
                #fetch.max.bytes: 200000
                fetch.max.wait.ms: 10000
                #max.partition.fetch.bytes: 2000000
                enableDlq: false
                autoCommitOffset: false
              contentType: application/json


