spring:
  cloud:
    config:
      enabled: false
    stream:
      bindings:
        processStyle-in-0:
          destination: TP.STYLE
          group: CG.STYLE
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultipler: 2
            backOffMaxInterval: 8000
      kafka:
        binder:
          brokers: localhost:9092
          consumerProperties:
            key.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            basic.auth.user.info:
            spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
        bindings:
          processStyle-in-0:
            consumer:
              enableDlq: false
              autoCommitOffset: false
            contentType: application/json

